variables:
  regex: '<version.light[a-z-]+4j>\d\.\d\.\d</version.light[a-z-]+4j>'
  regex1: '<artifactId>light-eventuate-4j</artifactId>\n\s+<version>\d\.\d\.\d</version>\n\s+<relativePath>..</relativePath>'
paths:
- path: pom.xml
  match: "{{ .regex }}"
  replace: "{{ .old }}"
  with: "{{ .new }}"
  must_include:
    - modelVersion
    - groupId
    - artifactId
- type: pom.xml
  path: hybrid-command
  match: "{{ .regex1 }}"
  replace: "{{ .old }}"
  with: "{{ .new }}"
  must_include:
    - modelVersion
    - groupId
    - artifactId
- type: pom.xml
  path: hybrid-query
  match: "{{ .regex1 }}"
  replace: "{{ .old }}"
  with: "{{ .new }}"
  must_include:
    - modelVersion
    - groupId
    - artifactId
- type: todo-list.md
  path: docs/content/tutorial
  match: "{{ .regex }}"
  replace: "{{ .old }}"
  with: "{{ .new }}"
  must_include:
