version: "2"
#
# Services
#
services:
   command:
      build: ./command/
      volumes:
        - ./docker/command/config:/config
        - ./docker/command/service:/service
      ports:
        - 8083:8083
      networks:
          - localnet

   query:
      build: ./query/
      volumes:
        - ./docker/query/config:/config
        - ./docker/query/service:/service
      ports:
        - 8082:8082
      networks:
          - localnet


# Networks
#
networks:
  localnet:
    # driver: bridge
    external: true