---
description: Change Data Capture Service to relay event table updates to aggregate topics
dbType: mysql
dbHost: localhost
dbPort: 3306
dbUser: root
dbPass: rootpassword
dbName: eventuate
kafka: localhost:9092
zookeeper: localhost:2181
cdcDbUser: root
cdcDbPass: rootpassword
postgresDbHost: localhost
postgresDBPort: 5432
postgresDbUser: postgres
postgresDbPass: postgres
postgresDbName: postgres
